{% set name = "colour-science" %}
{% set version = "0.3.9" %}
{% set sha256 = "3b7e5a6464b3a6e8760c998472f99c360e7357af8f4cbbbe5ab85bf9902c299b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - matplotlib >=1.3.1
    - python
    - scipy >=0.16.0
    - six >=1.10.0

test:
  imports:
    - colour

about:
  home: http://colour-science.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Colour Science for Python'
  doc_url: http://colour.readthedocs.io/
  dev_url: http://github.com/colour-science/colour

extra:
  recipe-maintainers:
    - KelSolaar
    - MichaelMauderer
