{% set version = "0.3.15" %}

package:
  name: colour-science
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/colour-science/colour-science-{{ version }}.tar.gz
  sha256: 5bc2c4b57cb219e9cd5c5b9432a3e9e50fdc0b434df9102b9ddf96d8d4d8ac14

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - matplotlib >=1.3.1
    - python
    - scipy >=0.16.0
    - six >=1.10.0

test:
  imports:
    - colour

about:
  home: https://www.colour-science.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Colour Science for Python'
  doc_url: https://colour.readthedocs.io/
  dev_url: https://github.com/colour-science/colour

extra:
  recipe-maintainers:
    - KelSolaar
    - MichaelMauderer
