{% set version = "0.3.14" %}

package:
  name: colour-science
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/colour-science/colour-science-{{ version }}.tar.gz
  sha256: 7ce019150f07720f3da93504a0eea9b95a7291985bff00aaef78ff560831b92d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python
    - imageio
    - scipy >=0.16.0
    - six >=1.10.0
    # optinal/plotting
    - matplotlib >=1.3.1

test:
  imports:
    - colour

about:
  home: https://www.colour-science.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Colour Science for Python'
  doc_url: https://colour.readthedocs.io/
  dev_url: https://github.com/colour-science/colour

extra:
  recipe-maintainers:
    - KelSolaar
    - MichaelMauderer
