{% set name = "colour-science" %}
{% set version = "0.3.14" %}
{% set sha256 = "7ce019150f07720f3da93504a0eea9b95a7291985bff00aaef78ff560831b92d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - matplotlib >=1.3.1
    - python
    - scipy >=0.16.0
    - six >=1.10.0

test:
  imports:
    - colour

about:
  home: https://www.colour-science.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Colour Science for Python'
  doc_url: https://colour.readthedocs.io/
  dev_url: https://github.com/colour-science/colour

extra:
  recipe-maintainers:
    - KelSolaar
    - MichaelMauderer
