travis:
  secure:
    BINSTAR_TOKEN: MLWXJdnsKtWx38bT/F8i4oJ4cZysNGYpVnDQp8BMAIX2TlZd74JS/ghgFKeI4m1kimohEOEPTjnSlbl/Zlywjv9yPbyqAf2uQa3zECwa3/c+EyE+KiEqGDF+T1AGNjba+nMlRnZhPGTkToIP2zUVszPXzni5vkUe5cbxJ8jCMKrKwfM7kMuSp+a05rhOzucSNau2qvtrVNlVh7fYQwonC23n1gT4ftlo4f1I/IQAgw9st5peSkwCQPMP+soMtoCh17ZBUnhAjL44sJLF/c8dA9N9TyQ5BsJGvaG6+oVepc+16yDrgUW01Ucvrsg9yyuU3nlSiaLdK2XgfMITxQxfPKBWIEMVvpb3AeMk9ZQA3CE2LSYXb+6ifNVkE+h65rXsMFJPPQe4eMxvJTKxVlCcA0nsM/bP16J4V0C1P5w0DLKeHl1+s/OisXm8ZXydW9cayc36qqjm1jUVNJJxHgptD+pgxmifSFdCELTVMdTAmVKPhddNJyASkgwPXIxZ9VZU8koNv59C/uaSAEhZM2//pTeWAVxrmvg7slBEu5IbTNBuy4LmvouaF2afxzHnTbA2H3oYLKhBPEZvRdSDSMRsMOUUt9oiVqeBs4XstGy5lTucZh8Vbbx/IYfI49aen5rTd+Jqcj6TIyZCMc4u7hgZSR0R1PBEQQmWcyJ14Kjh5i4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
