travis:
  secure:
    BINSTAR_TOKEN: bCuZAALKJUlBkVW77jNYjiO42ricQo5X5nGNVtPrSkAEYbk8h+y0Bz+TpYAcJ9vyuAyhuX0BGi48NTCnOREfoyYwIrNl8Ca+HkGKgdfe9LLbfchZO2aeFNOapiM+/8Lawr4DTNBPJ4M1kQX7S+NZWwGcRMFIZ01b4ACYWznfloM/oj3Ef++q2Hb3eDgNuDSnM0+hY/TgHBRwbz1OO7LSvwa3jCdhZZeiNWJpZzh5EY4TDJEpMMfTjapat9Rbp0vx8JqSeZs7YixwFkduVkVxoiG9vc/LPzH71F9wvQ8acLSeONVc/zOp9faNY2oglbl6snL6QDI4ASGo74diLQCpdTeK8NuE6AH24DYbZHZajDNY4z//0MfDV39YIYcN++uPQ7kVxCAMJcKvmryVE01B6GDmRMIpz0SiFQpOTmKtH1acjQVplMta2rGSVtCBtx1bRXnQJ2z/1H1NyKC4pe3QtSTOCpk+x+NgTgBS0mdLGJf5BIIYluTTOrsPAAASYA1fQ9oEDHtp9sJk09MX5AVvB9NCw/4k5BsWKj8v+OYi2MX0qXnfIeDIvFsgSPXRtgsonQDvW3juAyrA7qx1wxlZz+I9ic4mpohHwemtwnBwcx/19yq3Fnk5/WNapZYbWi+dm6Rd4LR4+uW3W20W8uqTW77V+4Axgck4KWKLigj0OCo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
