travis:
  secure:
    BINSTAR_TOKEN: Gb+zMQgys58g6r/8uNtgzXAmvYy2uUxpoW9oxWct6Soa3WItQP4vV8Qk9K7QVIwMHaUnyI4fHx46nItFRN/hrWMbiHecffJ6dqJnM9Ia8akaGTDGOaOEMq3XkOAdYSmH2RfDl1LNXgexjyrGfgyFvTH0RL2oBjN3tLftOaaDC/NN8yXcllECFNwzWrRU6T688ItdBsdGzg7AiZQTiMQe6+t8Hzkc6dn25h4HUuSzpxAN2eVcy7yrW2nJtrB9EABY8Feam9ZL6MBJrZxCddUIh7x1Wq3SQj/SX7tUBWdIb1fnkCooWPT1nHVCv/Nm3Ew5F7P7z+l0R0vNLXpOgch0X/TyryLbGNmaeuNyv3E5EjeAPeW0jzGdUIeheqDKCpyCrCJhztdIh288/aXTL1V/aQI4TAwpJJqCgjID/ajHzoQY0RpjG6fVDtrIAbpj69/hujp1C5JuQzoy0LfZiVnz+LNF4MLqDv6OXE5syIWna7pWRpZRwoZNVZm51tSpscTQNPx6DpWWstkXEuCH7qXyXgzTthuJ1fE3KNvBUv/OhQ9n/1QSyiZjv2ESn821U6BzzspGgK9doshG2O3/yg/jmhFVMcNMQglQV4rln0EBL665dwR7Pjtydw/cfFJZzym2Sa7wpwIJOFChS7EW8RF6JNE5PxodE2qaFYeDJN7wgrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
